# Generated by Django 4.0.2 on 2022-04-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularFeatures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FeaturesName', models.CharField(max_length=200)),
                ('FeaturesDesc', models.CharField(max_length=2000)),
                ('FeaturesImages', models.ImageField(upload_to='')),
            ],
        ),
    ]
