# Generated by Django 4.0.2 on 2022-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_popularfeatures_featuresimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFeatures',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FeaturesName', models.CharField(max_length=200)),
                ('FeaturesDesc', models.CharField(max_length=2000)),
                ('FeaturesImages', models.ImageField(upload_to='', verbose_name='/media/images/')),
            ],
        ),
    ]
