# Generated by Django 4.0.2 on 2022-05-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_allfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FeatureName', models.CharField(max_length=50)),
                ('FeatureDesc', models.CharField(max_length=500)),
                ('FeatureExt', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=200)),
                ('fileId', models.IntegerField()),
            ],
        ),
    ]
