# Generated by Django 4.0.2 on 2022-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_featuredetails_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='upload',
            field=models.FileField(default='null', upload_to='media/unConverted'),
        ),
    ]
