# Generated by Django 4.0.3 on 2022-05-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_allfeatures_featuresimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfeatures',
            name='FeaturesExt',
            field=models.CharField(default='', max_length=20),
        ),
    ]
