# Generated by Django 4.0.3 on 2022-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_allfeatures_featuresext'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularfeatures',
            name='FeaturesExt',
            field=models.CharField(default='', max_length=20),
        ),
    ]
