# Generated by Django 4.0.3 on 2022-05-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_popularfeatures_featuresext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('UnConverted', models.CharField(max_length=500)),
                ('Converted', models.CharField(max_length=500)),
            ],
        ),
    ]
