from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('MERGE PDF/', views.Merged, name='merge'),
    path('SPLIT PDF/', views.SplitPDF, name='split'),
    path('COMPRESS PDF/', views.CompressPDF, name='compress'),
    path('PDF TO WORD/', views.PDFtoWORD, name='pdftoword'),
    path('WORD TO PDF/', views.WORDtoPDF, name='wordtopdf'),
    path('PDF TO POWERPOINT/', views.PDFtoPOWERPOINT, name='pdftoppt'),
    path('POWERPOINT TO PDF/', views.POWERPOINTtoPDF, name='ppttopdf'),
    path('EXCEL TO PDF/', views.EDITPDF, name='exceltopdf'),
    path('PDF TO EXCEL/', views.PDFtoEXCEL, name='pdftoexcel'),
    path('PDF TO JPG/', views.PDFtoJPG, name='pdftojpg'),
    path('JPG TO PNG/', views.JPGtoPNG, name='jpgtopng'),
    path('HTML TO PDF/', views.HTMLtoPDF, name='htmltopdf'),
    path('MP4 TO MP3/', views.MP4toMP3, name='mp4tomp3'),
    path('LOCK PDF/', views.LOCKPDF, name='lockpdf'),
    path('UNLOCK PDF/', views.UNLOCKPDF, name='unclockpdf'),
    path('REPAIR PDF/', views.REPAIRPDF, name='repairpdf'),
    path('WORD READER/', views.WORDREADER, name='wordreader'),
    path('EXCEL READER/', views.EXCELREADER, name='excelreader'),
    path('POWERPOINT READER/', views.POWERPOINTREADER, name='pptreader'),
    path('EDIT PDF/', views.EDITPDF, name='editpdf'),
    path('PAGE NUMBER/', views.PAGENUMBER, name='pagenumber'),
    path('WATERMARK/', views.WATERMARK, name='watermark'),
    path('ROTATE PDF PAGES/', views.ROTATEPDFPAGES, name='rotatepdfpage'),
    path('SIGN PDF/', views.SIGNPDF, name='signpdf'),
    path('About/', views.About, name='about'),
    path('Contact/', views.Contact, name='contact'),
    path('Tools/', views.Tools, name='tools'),
    path('Login/', views.Login, name='login'),
    path('SignUp/', views.SignUp, name='signup'),
    path('FileUpload/', views.FileUpload, name='fileupload'),
    path('iVerify/', views.Verify, name='verify'),
    path('PopularFeatures/', views.popularFeatures, name='popularFeature'),
    path('PopularFeatures/<int:id>', views.popularFeaturesId, name='popularFeature'),
    path('AllFeatures/', views.allFeatures, name='allFeatures'),
    path('AllFeatures/<int:id>', views.allFeaturesId, name='allFeatures'),
]